/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DemoVscroll {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface VirtualScroll {
        "height": number;
        "onScrollReachedBottom": { () };
        "renderAhead": number;
        "rowCount": number;
        "rowHeight": number;
        "rowRenderer": any;
        "target": string;
        "type": string;
    }
}
declare global {
    interface HTMLDemoVscrollElement extends Components.DemoVscroll, HTMLStencilElement {
    }
    var HTMLDemoVscrollElement: {
        prototype: HTMLDemoVscrollElement;
        new (): HTMLDemoVscrollElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLVirtualScrollElement extends Components.VirtualScroll, HTMLStencilElement {
    }
    var HTMLVirtualScrollElement: {
        prototype: HTMLVirtualScrollElement;
        new (): HTMLVirtualScrollElement;
    };
    interface HTMLElementTagNameMap {
        "demo-vscroll": HTMLDemoVscrollElement;
        "my-component": HTMLMyComponentElement;
        "virtual-scroll": HTMLVirtualScrollElement;
    }
}
declare namespace LocalJSX {
    interface DemoVscroll {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface VirtualScroll {
        "height"?: number;
        "onScrollReachedBottom"?: { () };
        "renderAhead"?: number;
        "rowCount"?: number;
        "rowHeight"?: number;
        "rowRenderer"?: any;
        "target"?: string;
        "type"?: string;
    }
    interface IntrinsicElements {
        "demo-vscroll": DemoVscroll;
        "my-component": MyComponent;
        "virtual-scroll": VirtualScroll;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "demo-vscroll": LocalJSX.DemoVscroll & JSXBase.HTMLAttributes<HTMLDemoVscrollElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "virtual-scroll": LocalJSX.VirtualScroll & JSXBase.HTMLAttributes<HTMLVirtualScrollElement>;
        }
    }
}
